class_name: data_utils.datamodule.AsocaClassificationDataModule
params:
  patch_size: 68
  sample_every_epoch: true
  data_dir: dataset/classification
  sourcepath: dataset/ASOCA2020Data.zip
  perc_per_epoch_train: 1.0
  perc_per_epoch_val: 1.0