dataset:
  batch_size: 1
  weight_update_step: 0.
trainer:
  gpus: 4
  max_epochs: 100
model:
  lr: 0.001
  loss_type: dice # one of [dice, bce, dicebce, dicebceohnm]
  ohnm_ratio: 100
  optim_type: adam # one of [sgd, adam]
  fast_val: false
  skip_empty_patches: false