dataset:
    patch_size:  [128, 128, 128] # [80, 192, 160]
    patch_stride: [108, 108, 108] # [70, 182, 150]
    normalize: True
    data_clip_range: percentile # None, percentile, [0, 400]
    num_workers: 4
    resample_vols: false
    oversample: true
    crop_empty: false
    data_dir: dataset/processed
    sourcepath: dataset/ASOCA2020Data.zip
train:
    model: eunet # one of [cnn, unet, cubereg, icoreg, scnn, mobilenet, eunet]
    gpus: 1
    n_epochs: 100
    batch_size: 1
    lr: 0.001
    auto_lr_find: false
    loss_type: dicebceohnm # one of [dice, bce, dicebce, dicebceohnm]
    fully_conv: true
    fast_val: false
    skip_empty_patches: false
    mask_heart: false
    optim_type: adam # one of [sgd, adam]
    kernel_size: 3
    # model specific params
    unet:
        deep_supervision: false
    cnn:
        arch: default
