dataset:
    patch_size:  [128, 128, 128] # [80, 192, 160]
    patch_stride: [108, 108, 108] # [70, 182, 150]
    normalize: True
    data_clip_range: percentile # None, percentile, [0, 400]
    num_workers: 4
    resample_vols: false
    oversample: true
    crop_empty: false
    weight_update_step: 0
    perc_per_epoch_train: 0.25
    perc_per_epoch_val: 1
    sample_every_epoch: true
    data_dir: dataset/processed
    # sourcepath: dataset/3D_MNIST_DATA.zip 
    sourcepath: dataset/ASOCA2020Data.zip
train:
    model: cubereg # one of [cnn, unet, cubereg, icoreg, scnn, mobilenet, eunet]
    gpus: 4
    n_epochs: 100
    batch_size: 1
    lr: 0.001
    auto_lr_find: false
    loss_type: dice # one of [dice, bce, dicebce, dicebceohnm]
    ohnm_ratio: 100
    fully_conv: true
    fast_val: false
    skip_empty_patches: false
    mask_heart: false
    optim_type: adam # one of [sgd, adam]
    kernel_size: 3
    # model specific params
    unet:
        deep_supervision: false
    cnn:
        arch: strided # one of [default, strided, patch64, fully_conv]
    cubereg:
        arch: mixed # one of [mixed, vert, regular]
    icoreg:
        arch: mixed # one of [mixed, vert, regular]
    steerable:
        repr_type: spherical # one of [trivial, spherical, so3]
    ft:
        grid_kwargs:
            type: cube # one of [tetra, cube, ico, thompson, random]
