program: train.py
method: bayes
metric:
    name: valid/dice
    goal: maximize
early_terminate:
    type: hyperband
    min_iter: 5
parameters:
    train.trainer.max_epochs:
        value: 10
    dataset:
        value: classification
    dataset.params.perc_per_epoch_train:
        value: 0.5
    dataset.params.perc_per_epoch_val:
        value: 0.5
    train:
        value: classification
    model:
        value: classification/cubereg
    train.model.lr:
        min: 0.00001
        max: 0.1
    train.model.optim_type:
        values: ['adam', 'sgd']
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}