program: train.py
method: bayes
metric:
    name: valid/dice
    goal: maximize
early_terminate:
    type: hyperband
    min_iter: 5
parameters:
    train.trainer.max_epochs:
        value: 10
    model:
        value: classification/cubereg
    train.model.lr:
        min: 0.00001
        max: 0.1
    model.params.repr_type:
        values: [trivial, spherical, so3]
    model.params.grid_kwargs.type:
        values: [tetra, cube, ico]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}